[workspace]
resolver = "2"
members = ["client_test", "server_test"]


[workspace.dependencies]
virga = { path = "/home/greatwall/code/virga", default-features = false, features = ["use-xtransport"]}

env_logger = "0.11"
log = "0.4"